apiVersion: v1
kind: Namespace
metadata:
  name: node-ip-webhook
  labels:
    # This namespace must be excluded from the Webhook since it contains the
    # Pods implementing the Webhook itself to prevent a catch-22.
    inject-node-ip: "false"
