# The controllers must be running under a Service Account
# that has admin access to the Secret and the Webhook objects.
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: node-ip-webhook
  name: controller
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: node-ip-webhook
  name: secret-admin
  labels:
    #rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    #resourceNames: ["node-ip-webhook-certs"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: node-ip-webhook
  name: controller-secret-admin
subjects:
- kind: ServiceAccount
  namespace: node-ip-webhook
  name: controller
roleRef:
  kind: Role
  name: secret-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-admin
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  #resourceNames: ["node-ip-webhook"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-ip-controller-webhook-admin
subjects:
- kind: ServiceAccount
  name: controller
  namespace: node-ip-webhook
roleRef:
  kind: ClusterRole
  name: webhook-admin
  apiGroup: rbac.authorization.k8s.io
---
# The Webhook must be running under a Service Account that can read the Secret.
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: node-ip-webhook
  name: webhook
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: node-ip-webhook
  name: secret-read
  labels:
  #rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  #resourceNames: ["node-ip-webhook-certs"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: node-ip-webhook
  name: webhook-secret-read
subjects:
- kind: ServiceAccount
  namespace: node-ip-webhook
  name: webhook
roleRef:
  kind: Role
  name: secret-read
  apiGroup: rbac.authorization.k8s.io
