apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: node-ip-webhook
  name: controller
  labels:
    app: controller
spec:
  selector:
    matchLabels:
      app: controller
  replicas: 1
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller
      containers:
        - name: controller
          image: github.com/JRBANCEL/MutatingAdmissionWebhook/cmd/controller
