apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: node-ip-webhook
  name: webhook
  labels:
    app: webhook
spec:
  selector:
    matchLabels:
      app: webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: webhook
    spec:
      serviceAccountName: webhook
      containers:
        - name: webhook
          image: github.com/JRBANCEL/MutatingAdmissionWebhook/cmd/webhook
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
