apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: node-ip-webhook
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: node-ip-webhook
      namespace: default
      path: "/mutate"
  failurePolicy: Fail
  name: node.ip.webhook
  namespaceSelector:
    matchExpressions:
    - key: node-ip-webhook
      operator: NotIn
      values: ["disabled"]
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]